export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_FAILURE= "PRODUCT_FAILURE"

export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
export const GET_PRODUCT_SUCCESS=" GET_PRODUCT_SUCCESS"

export const SET_PAGE="SET_PAGE"
//PATCH
export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS"